import { Component, VERSION, ViewChild, ElementRef, OnInit } from '@angular/core';
import * as mobilenet from '@tensorflow-models/mobilenet';
import * as wasm from '@tensorflow/tfjs-backend-webgl'
import * as tf from '@tensorflow/tfjs'
import { ToastrService } from 'ngx-toastr'; 
import * as _ from 'lodash'

export interface Prediction {
  className: string;
  probability: number;
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  constructor(private toastr: ToastrService) {
  }
  title = 'finalYearProject';
  public model: any;
  public backend: any;
  public loading = true;
  public imageSrc: any = String;
  public predictions!: Prediction[];
  public image = new Image();
  public url: any;
  spinner = false;
  public dataset: any =
    {
      'tench, Tinca tinca': true,
      'goldfish, Carassius auratus': true,
      'great white shark, white shark, man-eater, man-eating shark, ': true,
      'Carcharodon carcharias': true,
      'tiger shark, Galeocerdo cuvieri': true,
      'hammerhead, hammerhead shark': true,
      'electric ray, crampfish, numbfish, torpedo': true,
      'stingray': true,
      'cock': true,
      'hen': true,
      'ostrich, Struthio camelus': true,
      'brambling, Fringilla montifringilla': true,
      'goldfinch, Carduelis carduelis': true,
      'house finch, linnet, Carpodacus mexicanus': true,
      'junco, snowbird': true,
      'indigo bunting, indigo finch, indigo bird, Passerina cyanea': true,
      'robin, American robin, Turdus migratorius': true,
      'bulbul': true,
      'jay': true,
      'magpie': true,
      'chickadee': true,
      'water ouzel, dipper': true,
      'kite': true,
      'bald eagle, American eagle, Haliaeetus leucocephalus': true,
      'vulture': true,
      'great grey owl, great gray owl, Strix nebulosa': true,
      'European fire salamander, Salamandra salamandra': true,
      'common newt, Triturus vulgaris': true,
      'eft': true,
      'spotted salamander, Ambystoma maculatum': true,
      'axolotl, mud puppy, Ambystoma mexicanum': true,
      'bullfrog, Rana catesbeiana': true,
      'tree frog, tree-frog': true,
      'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui': true,
      'loggerhead, loggerhead turtle, Caretta caretta': true,
      'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea': true,
      'mud turtle': true,
      'terrapin': true,
      'box turtle, box tortoise': true,
      'banded gecko': true,
      'common iguana, iguana, Iguana iguana': true,
      'American chameleon, anole, Anolis carolinensis': true,
      'whiptail, whiptail lizard': true,
      'agama': true,
      'frilled lizard, Chlamydosaurus kingi': true,
      'alligator lizard': true,
      'Gila monster, Heloderma suspectum': true,
      'green lizard, Lacerta viridis': true,
      'African chameleon, Chamaeleo chamaeleon': true,
      'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, ': true,
      'Varanus komodoensis': true,
      'African crocodile, Nile crocodile, Crocodylus niloticus': true,
      'American alligator, Alligator mississipiensis': true,
      'triceratops': true,
      'thunder snake, worm snake, Carphophis amoenus': true,
      'ringneck snake, ring-necked snake, ring snake': true,
      'hognose snake, puff adder, sand viper': true,
      'green snake, grass snake': true,
      'king snake, kingsnake': true,
      'garter snake, grass snake': true,
      'water snake': true,
      'vine snake': true,
      'night snake, Hypsiglena torquata': true,
      'boa constrictor, Constrictor constrictor': true,
      'rock python, rock snake, Python sebae': true,
      'Indian cobra, Naja naja': true,
      'green mamba': true,
      'sea snake': true,
      'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus': true,
      'diamondback, diamondback rattlesnake, Crotalus adamanteus': true,
      'sidewinder, horned rattlesnake, Crotalus cerastes': true,
      'trilobite': true,
      'harvestman, daddy longlegs, Phalangium opilio': true,
      'scorpion': true,
      'black and gold garden spider, Argiope aurantia': true,
      'barn spider, Araneus cavaticus': true,
      'garden spider, Aranea diademata': true,
      'black widow, Latrodectus mactans': true,
      'tarantula': true,
      'wolf spider, hunting spider': true,
      'tick': true,
      'centipede': true,
      'black grouse': true,
      'ptarmigan': true,
      'ruffed grouse, partridge, Bonasa umbellus': true,
      'prairie chicken, prairie grouse, prairie fowl': true,
      'peacock': true,
      'quail': true,
      'partridge': true,
      'African grey, African gray, Psittacus erithacus': true,
      'macaw': true,
      'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita': true,
      'lorikeet': true,
      'coucal': true,
      'bee eater': true,
      'hornbill': true,
      'hummingbird': true,
      'jacamar': true,
      'toucan': true,
      'drake': true,
      'red-breasted merganser, Mergus serrator': true,
      'goose': true,
      'black swan, Cygnus atratus': true,
      'tusker': true,
      'echidna, spiny anteater, anteater': true,
      'platypus, duckbill, duckbilled platypus, duck-billed platypus, ': true,
      'Ornithorhynchus anatinus': true,
      'wallaby, brush kangaroo': true,
      'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus': true,
      'wombat': true,
      'jelly fish': true,
      'sea anemone, anemone': true,
      'brain coral': true,
      'flatworm, platyhelminth': true,
      'nematode, nematode worm, roundworm': true,
      'conch': true,
      'snail': true,
      'slug': true,
      'sea slug, nudibranch': true,
      'chiton, coat-of-mail shell, sea cradle, polyplacophore': true,
      'chambered nautilus, pearly nautilus, nautilus': true,
      'Dungeness crab, Cancer magister': true,
      'rock crab, Cancer irroratus': true,
      'fiddler crab': true,
      'king crab, Alaska crab, Alaskan king crab, Alaska king crab, ': true,
      'Paralithodes camtschatica': true,
      'American lobster, Northern lobster, Maine lobster, Homarus americanus': true,
      'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea ': true,
      'crawfish': true,
      'crayfish, crawfish, crawdad, crawdaddy': true,
      'hermit crab': true,
      'isopod': true,
      'white stork, Ciconia ciconia': true,
      'black stork, Ciconia nigra': true,
      'spoonbill': true,
      'flamingo': true,
      'little blue heron, Egretta caerulea': true,
      'American egret, great white heron, Egretta albus': true,
      'bittern': true,
      'crane': true,
      'limpkin, Aramus pictus': true,
      'European gallinule, Porphyrio porphyrio': true,
      'American coot, marsh hen, mud hen, water hen, Fulica americana': true,
      'bustard': true,
      'ruddy turnstone, Arenaria interpres': true,
      'red-backed sandpiper, dunlin, Erolia alpina': true,
      'redshank, Tringa totanus': true,
      'dowitcher': true,
      'oystercatcher, oyster catcher': true,
      'pelican': true,
      'king penguin, Aptenodytes patagonica': true,
      'albatross, mollymawk': true,
      'grey whale, gray whale, devilfish, Eschrichtius gibbosus, ': true,
      'Eschrichtius robustus': true,
      'killer whale, killer, orca, grampus, sea wolf, Orcinus orca': true,
      'dugong, Dugong dugon': true,
      'sea lion': true,
      'Chihuahua': true,
      'Japanese spaniel': true,
      'Maltese dog, Maltese terrier, Maltese': true,
      'Pekinese, Pekingese, Peke': true,
      'Shih-Tzu': true,
      'Blenheim spaniel': true,
      'papillon': true,
      'toy terrier': true,
      'Rhodesian ridgeback': true,
      'Afghan hound, Afghan': true,
      'basset, basset hound': true,
      'beagle': true,
      'bloodhound, sleuthhound': true,
      'bluetick': true,
      'black-and-tan coonhound': true,
      'Walker hound, Walker foxhound': true,
      'English foxhound': true,
      'redbone': true,
      'borzoi, Russian wolfhound': true,
      'Irish wolfhound': true,
      'Italian greyhound': true,
      'whippet': true,
      'Ibizan hound, Ibizan Podenco': true,
      'Norwegian elkhound, elkhound': true,
      'otterhound, otter hound': true,
      'Saluki, gazelle hound': true,
      'Scottish deerhound, deerhound': true,
      'Weimaraner': true,
      'Staffordshire bullterrier, Staffordshire bull terrier': true,
      'American Staffordshire terrier, Staffordshire terrier, American pit ': true,
      'bull terrier, pit bull terrier': true,
      'Bedlington terrier': true,
      'Border terrier': true,
      'Kerry blue terrier': true,
      'Irish terrier': true,
      'Norfolk terrier': true,
      'Norwich terrier': true,
      'Yorkshire terrier': true,
      'wire-haired fox terrier': true,
      'Lakeland terrier': true,
      'Sealyham terrier, Sealyham': true,
      'Airedale, Airedale terrier': true,
      'cairn, cairn terrier': true,
      'Australian terrier': true,
      'Dandie Dinmont, Dandie Dinmont terrier': true,
      'Boston bull, Boston terrier': true,
      'miniature schnauzer': true,
      'giant schnauzer': true,
      'standard schnauzer': true,
      'Scotch terrier, Scottish terrier, Scottie': true,
      'Tibetan terrier, chrysanthemum dog': true,
      'silky terrier, Sydney silky': true,
      'soft-coated wheaten terrier': true,
      'West Highland white terrier': true,
      'Lhasa, Lhasa apso': true,
      'flat-coated retriever': true,
      'curly-coated retriever': true,
      'golden retriever': true,
      'Labrador retriever': true,
      'Chesapeake Bay retriever': true,
      'German short-haired pointer': true,
      'vizsla, Hungarian pointer': true,
      'English setter': true,
      'Irish setter, red setter': true,
      'Gordon setter': true,
      'Brittany spaniel': true,
      'clumber, clumber spaniel': true,
      'English springer, English springer spaniel': true,
      'Welsh springer spaniel': true,
      'cocker spaniel, English cocker spaniel, cocker': true,
      'Sussex spaniel': true,
      'Irish water spaniel': true,
      'kuvasz': true,
      'schipperke': true,
      'groenendael': true,
      'malinois': true,
      'briard': true,
      'kelpie': true,
      'komondor': true,
      'Old English sheepdog, bobtail': true,
      'Shetland sheepdog, Shetland sheep dog, Shetland': true,
      'collie': true,
      'Border collie': true,
      'Bouvier des Flandres, Bouviers des Flandres': true,
      'Rottweiler': true,
      'German shepherd, German shepherd dog, German police dog, alsatian': true,
      'Doberman, Doberman pinscher': true,
      'miniature pinscher': true,
      'Greater Swiss Mountain dog': true,
      'Bernese mountain dog': true,
      'Appenzeller': true,
      'EntleBucher': true,
      'boxer': true,
      'bull mastiff': true,
      'Tibetan mastiff': true,
      'French bulldog': true,
      'Great Dane': true,
      'Saint Bernard, St Bernard': true,
      'Eskimo dog, husky': true,
      'malamute, malemute, Alaskan malamute': true,
      'Siberian husky': true,
      'dalmatian, coach dog, carriage dog': true,
      'affenpinscher, monkey pinscher, monkey dog': true,
      'basenji': true,
      'pug, pug-dog': true,
      'Leonberg': true,
      'Newfoundland, Newfoundland dog': true,
      'Great Pyrenees': true,
      'Samoyed, Samoyede': true,
      'Pomeranian': true,
      'chow, chow chow': true,
      'keeshond': true,
      'Brabancon griffon': true,
      'Pembroke, Pembroke Welsh corgi': true,
      'Cardigan, Cardigan Welsh corgi': true,
      'toy poodle': true,
      'miniature poodle': true,
      'standard poodle': true,
      'Mexican hairless': true,
      'timber wolf, grey wolf, gray wolf, Canis lupus': true,
      'white wolf, Arctic wolf, Canis lupus tundrarum': true,
      'red wolf, maned wolf, Canis rufus, Canis niger': true,
      'coyote, prairie wolf, brush wolf, Canis latrans': true,
      'dingo, warrigal, warragal, Canis dingo': true,
      'dhole, Cuon alpinus': true,
      'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus': true,
      'hyena, hyaena': true,
      'red fox, Vulpes vulpes': true,
      'kit fox, Vulpes macrotis': true,
      'Arctic fox, white fox, Alopex lagopus': true,
      'grey fox, gray fox, Urocyon cinereoargenteus': true,
      'tabby, tabby cat': true,
      'tiger cat': true,
      'Persian cat': true,
      'Siamese cat, Siamese': true,
      'Egyptian cat': true,
      'cougar, puma, catamount, mountain lion, painter, panther': true,
      'Felis concolor': true,
      'lynx, catamount': true,
      'leopard, Panthera pardus': true,
      'snow leopard, ounce, Panthera uncia': true,
      'jaguar, panther, Panthera onca, Felis onca': true,
      'lion, king of beasts, Panthera leo': true,
      'tiger, Panthera tigris': true,
      'cheetah, chetah, Acinonyx jubatus': true,
      'brown bear, bruin, Ursus arctos': true,
      'American black bear, black bear, Ursus americanus, Euarctos': true,
      'americanus': true,
      'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus': true,
      'sloth bear, Melursus ursinus, Ursus ursinus': true,
      'mongoose': true,
      'meerkat, mierkat': true,
      'tiger beetle': true,
      'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle': true,
      'ground beetle, carabid beetle': true,
      'long-horned beetle, longicorn, longicorn beetle': true,
      'leaf beetle, chrysomelid': true,
      'dung beetle': true,
      'rhinoceros beetle': true,
      'weevil': true,
      'fly': true,
      'bee': true,
      'ant, emmet, pismire': true,
      'grasshopper, hopper': true,
      'cricket': true,
      'walking stick, walkingstick, stick insect': true,
      'cockroach, roach': true,
      'mantis, mantid': true,
      'cicada, cicala': true,
      'leafhopper': true,
      'lacewing, lacewing fly': true,
      'dragonfly, darning needle, devil\'s darning needle, sewing needle, ': true,
      'snake feeder, snake doctor, mosquito hawk, skeeter hawk': true,
      'damselfly': true,
      'admiral': true,
      'ringlet, ringlet butterfly': true,
      'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus': true,
      'cabbage butterfly': true,
      'sulphur butterfly, sulfur butterfly': true,
      'lycaenid, lycaenid butterfly': true,
      'starfish, sea star': true,
      'sea urchin': true,
      'sea cucumber, holothurian': true,
      'wood rabbit, cottontail, cottontail rabbit': true,
      'hare': true,
      'Angora, Angora rabbit': true,
      'hamster': true,
      'porcupine, hedgehog': true,
      'fox squirrel, eastern fox squirrel, Sciurus niger': true,
      'marmot': true,
      'beaver': true,
      'guinea pig, Cavia cobaya': true,
      'sorrel': true,
      'zebra': true,
      'hog, pig, grunter, squealer, Sus scrofa': true,
      'wild boar, boar, Sus scrofa': true,
      'warthog': true,
      'hippopotamus, hippo, river horse, Hippopotamus amphibius': true,
      'ox': true,
      'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis': true,
      'bison': true,
      'ram, tup': true,
      'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky ': true,
      'Mountain sheep, Ovis canadensis': true,
      'ibex, Capra ibex': true,
      'hartebeest': true,
      'impala, Aepyceros melampus': true,
      'gazelle': true,
      'Arabian camel, dromedary, Camelus dromedarius': true,
      'llama': true,
      'weasel': true,
      'mink': true,
      'polecat, fitch, foulmart, foumart, Mustela putorius': true,
      'black-footed ferret, ferret, Mustela nigripes': true,
      'otter': true,
      'skunk, polecat, wood pussy': true,
      'badger': true,
      'armadillo': true,
      'three-toed sloth, ai, Bradypus tridactylus': true,
      'orangutan, orang, orangutang, Pongo pygmaeus': true,
      'gorilla, Gorilla gorilla': true,
      'chimpanzee, chimp, Pan troglodytes': true,
      'gibbon, Hylobates lar': true,
      'siamang, Hylobates syndactylus, Symphalangus syndactylus': true,
      'guenon, guenon monkey': true,
      'patas, hussar monkey, Erythrocebus patas': true,
      'baboon': true,
      'macaque': true,
      'langur': true,
      'colobus, colobus monkey': true,
      'proboscis monkey, Nasalis larvatus': true,
      'marmoset': true,
      'capuchin, ringtail, Cebus capucinus': true,
      'howler monkey, howler': true,
      'titi, titi monkey': true,
      'spider monkey, Ateles geoffroyi': true,
      'squirrel monkey, Saimiri sciureus': true,
      'Madagascar cat, ring-tailed lemur, Lemur catta': true,
      'indri, indris, Indri indri, Indri brevicaudatus': true,
      'Indian elephant, Elephas maximus': true,
      'African elephant, Loxodonta africana': true,
      'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens': true,
      'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca': true,
      'barracouta, snoek': true,
      'eel': true,
      'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus ': true,
      'kisutch': true,
      'rock beauty, Holocanthus tricolor': true,
      'anemone fish': true,
      'sturgeon': true,
      'gar, garfish, garpike, billfish, Lepisosteus osseus': true,
      'lionfish': true,
      'puffer, pufferfish, blowfish, globefish': true
    }

  @ViewChild('img')
  public imageEl!: ElementRef;
  public async ngOnInit(): Promise<void> {
    this.backend = await tf.setBackend('wasm')

  }

  public async fileChangeEvent(event: any): Promise<void> {
    console.log(event)
    this.model = await mobilenet.load();
    // this.loading = false;
    console.log(this.model, event.target.files[0])
    if (event.target.files && event.target.files[0]) {
      const reader = new FileReader();
      reader.readAsDataURL(event.target.files[0]);
      reader.onload = (res: any) => {
        this.url = reader.result
        this.imageSrc = res.target.result;
        this.image.src = this.imageSrc;
        setTimeout(async () => {
          const imgEl = this.imageEl.nativeElement;
          this.predictions = await this.model.classify(this.image);
          console.log(this.predictions)
          this.spinner = true
          if (_.has(this.dataset, this.predictions[0].className)) {
            this.toastr.success('The uploaded image is a metazoa.')
          } else {
            this.toastr.error("The uploded image is not a metazoa.")
          }
          //  toaster.success("success")
        }, 0);
      };
    }
  }
}
